// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieWebApi.Infrastructure.Data;

#nullable disable

namespace MovieWebApi.Infrastructure.Migr.SqlServer.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20221017104300_InitNewData3")]
    partial class InitNewData3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MovieWebApi.Domain.Core.Entities.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MovieId");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<double?>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Movie");

                    b.HasData(
                        new
                        {
                            Id = new Guid("01abbca8-664d-4b20-b5de-024705497d4a"),
                            Description = "This is film was made by Quentin Tarantino",
                            Name = "Pulp Fiction"
                        },
                        new
                        {
                            Id = new Guid("02abbca8-664d-4b20-b5de-024705497d4a"),
                            Description = "This is film was made by Guy Ritchie",
                            Name = "Snatch",
                            Rating = 3.0
                        });
                });

            modelBuilder.Entity("MovieWebApi.Domain.Core.Entities.MovieStarring", b =>
                {
                    b.Property<Guid>("MovieId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StarringId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("MovieId", "StarringId");

                    b.HasIndex("StarringId");

                    b.ToTable("MovieStarrings");
                });

            modelBuilder.Entity("MovieWebApi.Domain.Core.Entities.Starring", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("StarringId");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("SecondName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.ToTable("Starring");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11abbca8-664d-4b20-b5de-024705497d4a"),
                            Description = "One of the main character",
                            FirstName = "John",
                            SecondName = "Travolta"
                        },
                        new
                        {
                            Id = new Guid("12abbca8-664d-4b20-b5de-024705497d4a"),
                            Description = "One of the main character",
                            FirstName = "Samuel L.",
                            SecondName = "Jackson"
                        });
                });

            modelBuilder.Entity("MovieWebApi.Domain.Core.Entities.MovieStarring", b =>
                {
                    b.HasOne("MovieWebApi.Domain.Core.Entities.Movie", "Movie")
                        .WithMany("MovieStarrings")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieWebApi.Domain.Core.Entities.Starring", "Starring")
                        .WithMany("MovieStarrings")
                        .HasForeignKey("StarringId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("Starring");
                });

            modelBuilder.Entity("MovieWebApi.Domain.Core.Entities.Movie", b =>
                {
                    b.Navigation("MovieStarrings");
                });

            modelBuilder.Entity("MovieWebApi.Domain.Core.Entities.Starring", b =>
                {
                    b.Navigation("MovieStarrings");
                });
#pragma warning restore 612, 618
        }
    }
}
